version: '2'
services:
  postgres:
    image: postgres:9
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      args:
        UID: 1001
        GID: 1001
    user: 1001:1001
    image: misasa/machine_time
    working_dir: /machine_time
    environment:
      - "RAILS_ENV=development"
      - "REDIS_URL=redis://redis:6379"    
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./app:/machine_time/app
      - ./spec:/machine_time/spec
      - ./config:/machine_time/config
      - ./public:/machine_time/public
      - ./db:/machine_time/db
      #- stone_data:/mnt/database
    ports:
      - "3031:3000"
    depends_on:
      - postgres
volumes:
  postgres_data:
